### ISSUE TITLE
Not working as instructed with Postman

### ISSUE THREAD

**Issue by sam-travise** [cpapidas/Spring-Boot-OAuth2-JWT-MySQL#3]
Sending the GET Request to api/sample as shown in the screen shot (Authorization: Bearer <token> and Content-Type: application/json) returns html Login Page requesting username and password! What went wrong?
<html>
    <head>
        <title>Login Page</title>
    </head>
    <body onload='document.f.username.focus();'>
        <h3>Login with Username and Password</h3>
        <form name='f' action='/login' method='POST'>
            <table>
                <tr>
                    <td>User:</td>
                    <td>
                        <input type='text' name='username' value=''>
                    </td>
                </tr>
                <tr>
                    <td>Password:</td>
                    <td>
                        <input type='password' name='password'/>
                    </td>
                </tr>
                <tr>
                    <td colspan='2'>
                        <input name="submit" type="submit" value="Login"/>
                    </td>
                </tr>
                <input name="_csrf" type="hidden" value="65a09arl-85kb-4f4j3-8272-30780a29535e" />
            </table>
        </form>
    </body>
</html>

**Comment by cpapidas** [comment]
Are you sure that your request is correct?

**Comment by sam-travise** [comment]
Yes. If you update to the latest Spring Boot version, things go out of whack.
