### ISSUE TITLE
not working with client application

### ISSUE THREAD

**Issue by pakTech786** [cpapidas/Spring-Boot-OAuth2-JWT-MySQL#4]
I am using the same implementation with angular client running on xampp."curl -u my-trusted-client-with-secret:somesecret http://localhost:8080/oauth/token -d "grant_type=client_credentials"   This request is working well with postman and client on localhost:8080 but any other client cannot access this /oauth/token despite of using corsfilters and enabling cors on this specific endpoint.other endpoints are also accessible after enabling cors but only this endpoint is creating problem.

**Comment by cpapidas** [comment]
Please try to open the browser without security

 For OSX, open Terminal and run:

`$ open -a Google\ Chrome --args --disable-web-security --user-data-dir`

--user-data-dir required on Chrome 49+ on OSX

For Linux run:

`$ google-chrome --disable-web-security`

Also if you're trying to access local files for dev purposes like AJAX or JSON, you can use this flag too.

`-–allow-file-access-from-files`
For Windows go into the command prompt and go into the folder where Chrome.exe is and type

`chrome.exe --disable-web-security`

https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome
