### ISSUE TITLE
Show error method not be able to add

### ISSUE THREAD

**Issue by NABEEL-AHMED-JAMIL** [cpapidas/Spring-Boot-OAuth2-JWT-MySQL#9]
https://github.com/cpapidas/Spring-Boot-OAuth2-JWT-MySQL/blob/b0f741cc076eacf7717ff67c10af7173828afafe/src/main/java/Unmentionable/settings/security/OAuth2ServerConfiguration.java#L88

**Comment by cpapidas** [comment]
Could you please add a description to your issue I am not sure what is about. Also, don't forget that you can create a pull request to master branch and fix or change something. Thanks :)

**Comment by cpapidas** [comment]
Cool create a pull request in order to fix this issue
